### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ludeeus** [hacs/org#1]
This organization should probably have another "logo" then the default GitHub image:

![image](https://user-images.githubusercontent.com/15093472/67071885-f67e6880-f183-11e9-98b0-df03be4502b2.png)

If you got a suggestion that can be used please post it below.
**It must be something that _you_ have created, and it must be ok that it's used for this project.**

**Comment by KevDoy** [comment]
I'd like to take this on. 

Something similar to the Home Assistant logo but more of a store front.

**Comment by gurjarshakti** [comment]
Hey, @KevDoy can you share some reference or some idea around the logo you want?

**Comment by KevDoy** [comment]
@gurjarshakti I'm already working on it but thanks!

**Comment by KevDoy** [comment]
https://github.com/hacs/documentation/pull/4

**Comment by ludeeus** [comment]
Just perfect ❤️ 
Thank you @KevDoy

**Comment by KevDoy** [comment]
Appreciate it :)
